include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    # Removed Flutter-specific rule. Added more Dart-recommended lints for stricter code quality.
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - unnecessary_this
    - avoid_annotating_with_dynamic
